# Generated by Django 6.0.6 on 2026-07-15 13:17

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_stripe_price_id_alter_tenant_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='trial_end_date',
            field=models.DateTimeField(default=tenants.models.default_trial_end_date),
        ),
    ]
