# Generated by Django 6.0.6 on 2026-07-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_trial_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='company_email',
        ),
    ]
