# Generated by Django 6.0.6 on 2026-07-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
