# Generated by Django 6.0.6 on 2026-08-06 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='invoice_footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='invoice_prefix',
            field=models.CharField(default='INV', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='late_fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='payment_terms',
            field=models.CharField(default='Due on receipt', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
