# Generated by Django 6.0.6 on 2026-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Organization Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('viewer', 'Viewer'), ('supervisor', 'Supervisor')], default='staff', max_length=20),
        ),
    ]
