# Generated by Django 6.0.6 on 2026-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PharmaPro', max_length=100)),
                ('site_url', models.URLField(default='https://pharmapro.com')),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_email', models.EmailField(default='support@pharmapro.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='We are currently performing maintenance. Please check back later.')),
                ('primary_color', models.CharField(default='#2c3e50', max_length=7)),
                ('secondary_color', models.CharField(default='#3498db', max_length=7)),
                ('accent_color', models.CharField(default='#e74c3c', max_length=7)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='system/logos/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='system/favicons/')),
                ('allow_registration', models.BooleanField(default=True)),
                ('require_verification', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=60)),
                ('force_ssl', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_test_mode', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'accounts_system_settings',
            },
        ),
    ]
