# Generated by Django 6.0.6 on 2026-07-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_unit_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryalert',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20),
        ),
    ]
