# Generated by Django 6.0.6 on 2026-07-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_saleunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_fractional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale_unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
