# Generated by Django 6.0.6 on 2026-08-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryalert_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='decommission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock'), ('discontinued', 'Discontinued'), ('expired', 'Expired'), ('decommissioned', 'Decommissioned')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('waste', 'Waste'), ('damaged', 'Damaged Goods'), ('stolen', 'Stolen Items'), ('lost', 'Lost Items'), ('add_stock', 'Add Stock'), ('expired', 'Expired Goods'), ('decommissioned', 'Decommissioned')], max_length=20),
        ),
    ]
