# Generated by Django 6.0.6 on 2026-07-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
