# Generated by Django 6.0.6 on 2026-07-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_sale_customer_payment_payer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_email',
        ),
    ]
