# Generated by Django 6.0.6 on 2026-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
